### ISSUE TITLE
How to change speed a vehical? 

### ISSUE THREAD

**Issue by pvqu47** [JustInvoke/Randomation-Vehicle-Physics#33]

**Comment by JustInvoke** [comment]
There are a number of ways to change the speed of a vehicle:
- Increase the RPM range of the engine (make the torque curve on the engine wider/move points on the curve to the right).
- Reduce the ratios of gears in the transmission. Lower ratios indicate greater RPM output and lower torque.
- Increase the radius of wheels (tire radius specifically).

**Comment by pvqu47** [comment]
Thanks a lot! More a question, how to fixed speed of a vehicle in file code .cs?

**Comment by pvqu47** [comment]
Thanks! 😘
