### ISSUE TITLE
Option to turn off *vehicle almost always land on wheels after fall*, even when I turn off flip control

### ISSUE THREAD

**Issue by Renato404** [JustInvoke/Randomation-Vehicle-Physics#34]
I turned off vehicle assists, flip control and stunt detect scripts, and after fall vehicle always land on wheels no matter what crazy stunt I make. Is there way to turn it off? Or am I doing something wrong?

**Comment by JustInvoke** [comment]
The FlipControl script is what makes vehicles stay upright in the air, so as long as it's disabled the vehicle should not always land on its wheels. Does the problem happen with the default prefabs?

**Comment by Renato404** [comment]
Now there is no problems, Probably unity glitch. Yesterday, when I turned off that script it didn't take effect at all, and with other scripts too. My apologies for not trying to reset unity, Had similar problems before.

**Comment by JustInvoke** [comment]
No problem.
