### ISSUE TITLE
How to increase power of boost?

### ISSUE THREAD

**Issue by zelderus** [JustInvoke/Randomation-Vehicle-Physics#37]
I want much more power speed when boost. What a parameter I should change?

**Comment by zelderus** [comment]
Thanks. I have changed this curve, it has add some power, but so little. If I add much more in the curve in any axis, then some exception in math occurs.

**Comment by JustInvoke** [comment]
What kind of exception is happening?

**Comment by zelderus** [comment]
Wheel.cs - float EvaluateTorque(float t):
1. Assertion failed on expression: 'curveT >= GetRange().first && curveT <= GetRange().second'
UnityEngine.AnimationCurve:Evaluate(Single)
2. Assertion failed on expression: 'curveT >= m_Curve[lhs].time && curveT <= m_Curve[rhs].time'
UnityEngine.AnimationCurve:Evaluate(Single)

And other like this. This happen when I set y-axis much more (> 1.0 - I want super speed like rocket ;)) - car on small speed dont going, wheels fast rotating and drifting, and then this exceptions occurs. When I set y-axis less - boost power so little :(

**Comment by JustInvoke** [comment]
Well for now I can't pin down why the curve throws errors with large values. Clamping the input values for curve evaluations doesn't seem to fix it. One thing you can try is increasing the feedback RPM bias on the driven wheels if you haven't already. Maybe you can combine this with slightly lower boost values and increased forward friction on the wheels to keep the fast acceleration effect.

**Comment by zelderus** [comment]
> increased forward friction on the wheels
Thanks. That's what i wanted.
