### ISSUE TITLE
Please provide all steering modes , button,tilt and steering wheel mode...

### ISSUE THREAD

**Issue by waqazs** [JustInvoke/Randomation-Vehicle-Physics#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JustInvoke** [comment]
It looks like part of your issue was truncated and the body appears to only have the prompts asking you to detail the problem. Can you fill in the rest of the details so I can consider addressing them?
