### ISSUE TITLE
Just wondering if there's a fix for the car jump when driving fast on the edge of two colliders snapped together

### ISSUE THREAD

**Issue by mgsvevo** [JustInvoke/Randomation-Vehicle-Physics#43]
It happens sometimes
<img src="https://media.giphy.com/media/J4DRwIrWDKdsQnKbrF/giphy.gif" alt="HTML5 Icon" width="128" height="128">

**Comment by JustInvoke** [comment]
I don't have a fix unfortunately. You could try increasing the hard contact force on suspensions to avoid having vehicles get close enough to touch the ground in the first place.
