### ISSUE TITLE
Vehicle damage percent/ health bar

### ISSUE THREAD

**Issue by salvadorc17** [JustInvoke/Randomation-Vehicle-Physics#45]
Hi will be good to have a vehicle damage percent value, or health bar that show how much damaged is it and restores after repared.

**Comment by JustInvoke** [comment]
Sorry for the late reply, I've been busy with school.

The Motor class has a hidden variable called health that can roughly represent the damage amount for a vehicle, since it depends on the motor to run. The health ranges from 0 to 1.
