### ISSUE TITLE
Need Assistance, Tractor Rollover

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [JustInvoke/Randomation-Vehicle-Physics#47]
Hi i am new to RVP and need assistance. I just configure my vehicle(Tractor). But it rollover very quickly as i move left right with some speed.
Which value i should change? Check attached gif
![issue](https://user-images.githubusercontent.com/32755091/78812247-8a6b1780-79e4-11ea-891c-ab8ed29265fe.gif)

Thanks

**Comment by MuhammadWaqasOfficial** [comment]
anyone?

**Comment by JustInvoke** [comment]
Try lowering the center of mass offset on VehicleParent.

Also, I'm not actively "supporting" this so expect replies to potentially take a few days or longer.

**Comment by MuhammadWaqasOfficial** [comment]
Thanks for assistance. 
Its okay for  a  late response. Yes i know about discontinued of RVP from assets store. 
Thnaks brother
