### ISSUE TITLE
Can We Achieve Traffic Racer Game Like Control With RVP

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [JustInvoke/Randomation-Vehicle-Physics#48]
Hi, can we achieve famous [traffic racer game](https://play.google.com/store/apps/details?id=com.skgames.trafficracer) like control with this RVP control.
Regards
Muhammad Waqas

**Comment by JustInvoke** [comment]
You could probably make it work, but I think a physics package like this is overkill and you'll spend more time reeling in the physics to keep the cars on a straight path. The performance is also not great for mobile with that many cars.
