### ISSUE TITLE
Step by step tutorial?

### ISSUE THREAD

**Issue by giorgi-abashidze** [JustInvoke/Randomation-Vehicle-Physics#61]
can you record a video and explain how to setup all the thing? im trying to setup on some other 3d models and getting weird results, car parts are moving in random locations far from a car.

im trying to setup on this model: https://sketchfab.com/3d-models/apocalyptic-off-road-buggy-5aacc30acdc5455aac98f44f5bc8c043

**Comment by JustInvoke** [comment]
I haven't tried downloading that model but my first instinct is to check the origins of the car part models. They might be at the origin of the entire vehicle when they should be at the center of the geometry of each part. Otherwise parts are likely to rotate around the origin of the vehicle, appearing like large random offsets.

**Comment by giorgi-abashidze** [comment]
> I haven't tried downloading that model but my first instinct is to check the origins of the car part models. They might be at the origin of the entire vehicle when they should be at the center of the geometry of each part. Otherwise parts are likely to rotate around the origin of the vehicle, appearing like large random offsets.

no i edited model in blender and separated required parts and set origin to center of geometry but still unable to setup properly. 

link of the edited model: https://drive.google.com/file/d/1jIj9UQGE876jSONXhWar1oEXdsqKq9ve/view?usp=sharing

**Comment by giorgi-abashidze** [comment]
wheel collider appearing in center of a car but wheel got origin to geometry
![Screenshot 2023-09-06 204117](https://github.com/JustInvoke/Randomation-Vehicle-Physics/assets/52792051/d6e41a39-2500-47c4-8c9c-3295df450aa8)

**Comment by giorgi-abashidze** [comment]
well after struggling whole day, I fixed positions but now rotation is a problem, when exporting z forward from blender car forward is z in unity but still not working because rotation y is -180 by default

**Comment by giorgi-abashidze** [comment]
we really need tutorial about that rotations and positions

**Comment by JustInvoke** [comment]
If rotation on the y-axis is -180 by default maybe you could put the object inside of a parent object and rotate that to fix it. Sorry I haven't really worked much with the asset since 2016 and I don't really support it anymore or have time to.

**Comment by giorgi-abashidze** [comment]
> If rotation on the y-axis is -180 by default maybe you could put the object inside of a parent object and rotate that to fix it. Sorry I haven't really worked much with the asset since 2016 and I don't really support it anymore or have time to.

ok thanks
